from fpdf import FPDF
import datetime

def generate_sustainability_report(pue, active_nodes, power_saved_kw, co2_saved_tons):
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Header Section
    pdf.set_font("Arial", 'B', 16)
    # Emerald green title
    pdf.set_text_color(16, 185, 129) 
    pdf.cell(200, 10, txt="GreenCloud-AI: Sustainability Audit Report", ln=True, align='C')
    
    # Timestamp
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(100, 100, 100)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(200, 10, txt=f"Generated on: {date_str}", ln=True, align='C')
    pdf.ln(10)
    
    # 2. System Performance Body
    pdf.set_font("Arial", size=12)
    pdf.set_text_color(0, 0, 0)
    
    pdf.cell(200, 10, txt="System Performance Overview:", ln=True)
    pdf.cell(200, 10, txt=f" - Current Power Usage Effectiveness (PUE): {pue}", ln=True)
    pdf.cell(200, 10, txt=f" - Active Rack Nodes: {active_nodes}", ln=True)
    pdf.ln(10)
    
    # 3. Environmental Impact Body
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt="Environmental Impact & AI Optimization:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f" - Total Power Saved by Deep Sleep: {power_saved_kw} kW", ln=True)
    pdf.cell(200, 10, txt=f" - Cumulative CO2e Reduced: {co2_saved_tons} Tons", ln=True)
    
    # Footer
    pdf.ln(30)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(200, 10, txt="Automated report generated by the GreenCloud-AI ML Engine.", ln=True, align='C')
    
    # 4. Save the File
    filename = "GreenCloud_Sustainability_Report.pdf"
    pdf.output(filename)
    print(f"✅ Report successfully generated: {filename}")

if __name__ == "__main__":
    # Test the generator with simulated end-of-demo data
    generate_sustainability_report(
        pue="1.14", 
        active_nodes="68/90", 
        power_saved_kw=712.4, 
        co2_saved_tons=4.81
    )